version: "3.1"
services:
  listing-service:
    build: "./listing-service"
    depends_on:
      - listing-service-db
    volumes:
      - ./listing-service:/opt/app

  listing-service-db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports: 
        - 0.0.0.0:7200:5432

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports: 
        - 0.0.0.0:7201:5432
